name: Create Disk Image Action
description: Creates a disk image in multiple formats (Windows only)
branding:
  icon: 'plus-circle'
  color: 'blue'
inputs:
  filename:
     description: 'The name of the file when saved to a disk image file'
     required: true
     default: 'image.iso'
  path:
     description: 'The path where the files are stored that need to be included in the disk image'
     required: true
     default: '.\'
  label:
     description: 'The label that is used for the disk image in ISO9660 format'
     required: false
runs:
  using: "composite"
  steps:
    - name: Install ImgBurn
      run: choco install imgburn -y
      shell: pwsh
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Create disk image  
      run: '"%programfiles(x86)%\ImgBurn\ImgBurn.exe" /MODE BUILD /BUILDINPUTMODE STANDARD /BUILDOUTPUTMODE IMAGEFILE /SRC "${{ github.WORKSPACE }}\${{ inputs.path }}" /DEST "${{ github.WORKSPACE }}\${{ inputs.filename }}" /FILESYSTEM "ISO9660 + Joliet" /VOLUMELABEL_ISO9660 "${{ inputs.label }}" /VOLUMELABEL_JOLIET "${{ inputs.label }}" /OVERWRITE YES /ROOTFOLDER YES /START /CLOSE /NOIMAGEDETAILS'
      shell: cmd
    - name: Upload disk image binary as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.filename }}
        path: ${{ github.WORKSPACE }}\${{ inputs.filename }}
