name: Test
on:
  push:
  workflow_dispatch:
jobs:
 test:
  runs-on: windows-latest
  steps:
   - uses: Minionguyjpro/Create-Disk-Image@${{ github.ref_name }}
     with:
       path: example
       filename: test.iso
       label: Example
       push: true
