name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
 test:
  runs-on: windows-latest
  steps:
   - name: Test disk image
     uses: Minionguyjpro/Create-Disk-Image@main
     with:
       path: example
       filename: test.iso
       label: Example
       push: true
       output-dir: example
